spring.application.name=Project-02_SpringbootRestApi_EmployeeManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/emp_managemet_db
spring.datasource.username=sarafat
spring.datasource.password=sarafat@123
spring.jpa.hibernate.ddl-auto= update
server.port= 8088
spring.jpa.show-sql=true
